//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomRentalManagementProj.SysModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IdReceipt { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<long> AmountCharged { get; set; }
        public Nullable<long> TaxAmount { get; set; }
        public Nullable<long> PaymentTotal { get; set; }
    }
}
