//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomRentalManagementProj.SysModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int IdRoom { get; set; }
        public string RoomType { get; set; }
        public string BedType { get; set; }
        public Nullable<long> Rate { get; set; }
        public string Status { get; set; }
    }
}
